/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fescfafic.imagempdi.classes;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gutemberg
 */
public class Principal extends javax.swing.JFrame {
    
    private BufferedImage img;
    private BufferedImage imgAtual;
    
    /**
     * Creates new form Imagem
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        salvar = new javax.swing.JMenuItem();
        limpar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        grayscaleRed = new javax.swing.JMenuItem();
        grayscaleGreen = new javax.swing.JMenuItem();
        grayscaleBlue = new javax.swing.JMenuItem();
        grayscaleMedia = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        bandaSeparadaRed = new javax.swing.JMenuItem();
        bandaSeparadaGreen = new javax.swing.JMenuItem();
        bandaSeparadaBlue = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        limiar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processamento Digital de Imagens");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Imagem Original");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Desenvolvido por: Gutemberg Ferreira Dantas - 4° Período - Ciência da Computação");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Imagem Editada");
        jLabel4.setToolTipText("");

        jMenu2.setText("Imagem");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu2.add(abrir);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jMenu2.add(salvar);

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jMenu2.add(limpar);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Editar");

        jMenu3.setText("Tons de Cinza");

        grayscaleRed.setText("Red");
        grayscaleRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleRedActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleRed);

        grayscaleGreen.setText("Green");
        grayscaleGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleGreenActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleGreen);

        grayscaleBlue.setText("Blue");
        grayscaleBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleBlueActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleBlue);

        grayscaleMedia.setText("Media");
        grayscaleMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleMediaActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleMedia);

        jMenu1.add(jMenu3);

        jMenu4.setText("Banda de Cores");

        bandaSeparadaRed.setText("Red");
        bandaSeparadaRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaSeparadaRedActionPerformed(evt);
            }
        });
        jMenu4.add(bandaSeparadaRed);

        bandaSeparadaGreen.setText("Green");
        bandaSeparadaGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaSeparadaGreenActionPerformed(evt);
            }
        });
        jMenu4.add(bandaSeparadaGreen);

        bandaSeparadaBlue.setText("Blue");
        bandaSeparadaBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaSeparadaBlueActionPerformed(evt);
            }
        });
        jMenu4.add(bandaSeparadaBlue);

        jMenu1.add(jMenu4);

        jMenu5.setText("Negativo");

        jMenuItem1.setText("Em RGB");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Em Y");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenu1.add(jMenu5);

        jMenu6.setText("Brilho");

        jMenuItem3.setText("Aditivo RGB");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem5.setText("Aditivo Y");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Multi. RGB");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("Multi. Y");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenu1.add(jMenu6);

        jMenu7.setText("Operações Locais");

        jMenuItem8.setText("Filtro Média 3x3");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenu1.add(jMenu7);

        limiar.setText("Limiar");
        limiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limiarActionPerformed(evt);
            }
        });
        jMenu1.add(limiar);

        jMenuItem4.setText("YIQ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel4});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void exibirImagem(BufferedImage buffer, BufferedImage img){
        jLabel1.setIcon(new ImageIcon(img));
        jLabel4.setIcon(new ImageIcon(buffer));
        imgAtual = buffer;
    }
    
    private void grayscaleRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleRedActionPerformed
        BufferedImage buffer = new Imagem().grayscaleRed(img); 
        exibirImagem(buffer, img);
    }//GEN-LAST:event_grayscaleRedActionPerformed

    private void grayscaleGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleGreenActionPerformed
        BufferedImage buffer = new Imagem().grayscaleGreen(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_grayscaleGreenActionPerformed

    private void grayscaleBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleBlueActionPerformed
        BufferedImage buffer = new Imagem().grayscaleBlue(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_grayscaleBlueActionPerformed

    private void grayscaleMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleMediaActionPerformed
        BufferedImage buffer = new Imagem().grayscaleMedia(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_grayscaleMediaActionPerformed
    
    private void bandaSeparadaRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaSeparadaRedActionPerformed
        BufferedImage buffer = new Imagem().bandaCorRed(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_bandaSeparadaRedActionPerformed

    private void bandaSeparadaGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaSeparadaGreenActionPerformed
        BufferedImage buffer = new Imagem().bandaCorGreen(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_bandaSeparadaGreenActionPerformed

    private void bandaSeparadaBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaSeparadaBlueActionPerformed
        BufferedImage buffer = new Imagem().bandaCorBlue(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_bandaSeparadaBlueActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        exibirImagem();
    }//GEN-LAST:event_abrirActionPerformed
    
    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        jLabel1.setIcon(null);
        jLabel4.setIcon(null);
        jLabel1.setText("Imagem Original");
        jLabel2.setText("");
        jLabel4.setText("Imagem Editada");
        img = null;
        imgAtual = null;
    }//GEN-LAST:event_limparActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        new Imagem().salvarImagem(imgAtual);
    }//GEN-LAST:event_salvarActionPerformed

    private void limiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limiarActionPerformed
        String nivel = JOptionPane.showInputDialog("Informe o nível");
        BufferedImage buffer = new Imagem().limiarizar(img, 
                Integer.parseInt(nivel));
        exibirImagem(buffer, img);
    }//GEN-LAST:event_limiarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        BufferedImage buffer = new Imagem().negativoRGB(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Imagem i = new Imagem();
        double[][][] matriz = i.rgb2Yiq(img);
        BufferedImage buffer = new Imagem().yiq2Rgb(matriz, img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        BufferedImage buffer = new Imagem().negativoY(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String quantidadeBrilho = 
                JOptionPane.showInputDialog("Informe a quantidade de brilho");
        BufferedImage buffer = new Imagem().aditivoRGB(img,
                Integer.parseInt(quantidadeBrilho));
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        String quantidadeBrilho =
                JOptionPane.showInputDialog("Informe a quantidade de brilho");
        BufferedImage buffer = new Imagem().aditivoY(img,
                Integer.parseInt(quantidadeBrilho));
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        String quantidadeBrilho = 
                JOptionPane.showInputDialog("Informe a quantidade de brilho");
        BufferedImage buffer = new Imagem().multiRGB(img, 
                Double.parseDouble(quantidadeBrilho));
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        String quantidadeBrilho = 
                JOptionPane.showInputDialog("Informe a quantidade de brilho");
        BufferedImage buffer = new Imagem().multiY(img, 
                Double.parseDouble(quantidadeBrilho));
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        BufferedImage buffer = new Imagem().mediaSuavizacao(img);
        exibirImagem(buffer, img);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void exibirImagem(){
        img = new Imagem().abrirImagem(img);
        
        ImageIcon i = new ImageIcon(img);
        jLabel1.setIcon(i);
        jLabel1.setText("");
        jLabel4.setText("");
        
        jLabel2.setText("Quantidade de pixels: " 
                + new Imagem().quantidadePixels(img));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenuItem bandaSeparadaBlue;
    private javax.swing.JMenuItem bandaSeparadaGreen;
    private javax.swing.JMenuItem bandaSeparadaRed;
    private javax.swing.JMenuItem grayscaleBlue;
    private javax.swing.JMenuItem grayscaleGreen;
    private javax.swing.JMenuItem grayscaleMedia;
    private javax.swing.JMenuItem grayscaleRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem limiar;
    private javax.swing.JMenuItem limpar;
    private javax.swing.JMenuItem salvar;
    // End of variables declaration//GEN-END:variables
}
